### ISSUE TITLE
Devise 寄信功能

### ISSUE THREAD

**Issue by serenanamee** [SlackClone/slack_clone#16]
目標： 
-  [x] 成功寄信

流程：
-  [x] devise.rb 設定
-  [x] config/environments/development.rb 環境設定
-  [x] 新增 smtp_settings 的 config/email.yml
-  [x]  設定 RAILS_ENV 變數在 application.yml 內
-  [x]  複製 RAILS_ENV 變數在 application.example.yml

added

pages.html.erb  新增兩個連結

**Comment by yuka1981** [comment]
請問 mail driver 的參考連結為什麼是 PHP laravel 的設定啊？

**Comment by serenanamee** [comment]
現在來處理一下
